# catalog/data.py
# Conteúdo fixo do site. Sem banco de dados — editar este arquivo é o
# equivalente a "cadastrar" uma distro, DE ou pergunta do quiz.

DISTROS = [
    # --- Bases ---
    {
        "slug": "debian",
        "name": "Debian",
        "base_slug": None,
        "category": "base",
        "short_description": "A base estável por trás de boa parte do ecossistema Linux.",
        "long_description": "Debian é um dos projetos mais antigos e estáveis do Linux, servindo de fundação para Ubuntu e dezenas de outras distros. Prioriza estabilidade acima de tudo — pacotes são testados exaustivamente antes de entrar na versão estável.",
        "nvidia_support": "moderado",
        "has_good_docs": True,
        "default_de": "GNOME",
        "official_url": "https://www.debian.org",
    },
    {
        "slug": "arch",
        "name": "Arch Linux",
        "base_slug": None,
        "category": "avancado",
        "short_description": "Rolling release minimalista, você monta tudo do zero.",
        "long_description": "Arch entrega um sistema mínimo e deixa cada decisão de configuração com o usuário. É a base de aprendizado mais citada da comunidade Linux, e também a base de distros populares como Manjaro, CachyOS e SteamOS.",
        "nvidia_support": "sim (configuração manual)",
        "has_good_docs": True,
        "default_de": "nenhum (à escolha)",
        "official_url": "https://archlinux.org",
    },
    {
        "slug": "fedora",
        "name": "Fedora",
        "base_slug": None,
        "category": "intermediario",
        "short_description": "Estável, atualizada e patrocinada pela Red Hat.",
        "long_description": "Fedora equilibra estabilidade com pacotes relativamente recentes. É o laboratório onde tecnologias que depois chegam ao RHEL são testadas primeiro. Boa escolha para quem quer algo moderno sem abrir mão de solidez.",
        "nvidia_support": "sim (via RPM Fusion)",
        "has_good_docs": True,
        "default_de": "GNOME",
        "official_url": "https://fedoraproject.org",
    },
    {
        "slug": "opensuse-leap",
        "name": "openSUSE Leap",
        "base_slug": None,
        "category": "intermediario",
        "short_description": "Estável, com ferramentas de administração muito maduras.",
        "long_description": "openSUSE Leap é a versão estável do openSUSE, com o YaST como diferencial — uma ferramenta de administração gráfica que cobre praticamente qualquer configuração do sistema.",
        "nvidia_support": "sim (via repositórios)",
        "has_good_docs": True,
        "default_de": "KDE Plasma",
        "official_url": "https://www.opensuse.org",
    },
    {
        "slug": "opensuse-tumbleweed",
        "name": "openSUSE Tumbleweed",
        "base_slug": None,
        "category": "intermediario",
        "short_description": "Rolling release do openSUSE, mas com testes rigorosos antes de liberar pacotes.",
        "long_description": "Tumbleweed entrega os pacotes mais recentes assim que passam por uma bateria automatizada de testes, um equilíbrio raro entre atualização constante e estabilidade.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "KDE Plasma",
        "official_url": "https://www.opensuse.org",
    },
    {
        "slug": "void",
        "name": "Void Linux",
        "base_slug": None,
        "category": "avancado",
        "short_description": "Rolling release independente, com o próprio gerenciador de pacotes e init.",
        "long_description": "Void não deriva de nenhuma outra distro — tem gerenciador de pacotes (xbps) e sistema de init (runit) próprios, em vez do systemd. Voltada para quem gosta de entender cada camada do sistema.",
        "nvidia_support": "limitado (configuração manual)",
        "has_good_docs": True,
        "default_de": "nenhum (à escolha)",
        "official_url": "https://voidlinux.org",
    },
    {
        "slug": "gentoo",
        "name": "Gentoo",
        "base_slug": None,
        "category": "avancado",
        "short_description": "Você compila o sistema a partir do código-fonte.",
        "long_description": "Gentoo é o extremo da personalização: praticamente todo o sistema é compilado localmente a partir do código-fonte, com flags de otimização escolhidas por você. É mais um exercício de aprendizado do que uma distro do dia a dia.",
        "nvidia_support": "sim (configuração manual)",
        "has_good_docs": True,
        "default_de": "nenhum (à escolha)",
        "official_url": "https://www.gentoo.org",
    },
    {
        "slug": "slackware",
        "name": "Slackware",
        "base_slug": None,
        "category": "avancado",
        "short_description": "A distro Linux ativa mais antiga que existe.",
        "long_description": "Slackware segue uma filosofia de simplicidade radical: sem resolução automática de dependências, sem ferramentas gráficas de configuração. Ideal para quem quer aprender o Linux por baixo dos panos.",
        "nvidia_support": "sim (configuração manual)",
        "has_good_docs": True,
        "default_de": "KDE Plasma / XFCE",
        "official_url": "http://www.slackware.com",
    },

    # --- Derivadas de Debian ---
    {
        "slug": "ubuntu",
        "name": "Ubuntu",
        "base_slug": "debian",
        "category": "iniciante",
        "short_description": "A distro mais generalista e documentada do ecossistema.",
        "long_description": "Ubuntu é o ponto de entrada mais comum no Linux: grande comunidade, compatibilidade ampla com software de terceiros e suporte comercial disponível via Canonical. Faz telemetria opcional, mas é totalmente desativável.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "GNOME",
        "official_url": "https://ubuntu.com",
    },
    {
        "slug": "zorin",
        "name": "Zorin OS",
        "base_slug": "ubuntu",
        "category": "iniciante",
        "short_description": "Interface pensada para quem vem do Windows.",
        "long_description": "Zorin OS reorganiza a interface do GNOME pra lembrar o Windows de cara, o que reduz o choque de quem está migrando. Tem boa documentação e comunidade ativa.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "Zorin Desktop (GNOME customizado)",
        "official_url": "https://zorin.com/os",
    },
    {
        "slug": "mint",
        "name": "Linux Mint",
        "base_slug": "ubuntu",
        "category": "iniciante",
        "short_description": "Estável, leve e uma das portas de entrada mais recomendadas.",
        "long_description": "Linux Mint usa o Cinnamon, um ambiente de trabalho tradicional e familiar. É conhecido por ser extremamente estável e por não seguir tendências arriscadas — prioriza que tudo simplesmente funcione.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "Cinnamon",
        "official_url": "https://linuxmint.com",
    },
    {
        "slug": "pop-os",
        "name": "Pop!_OS",
        "base_slug": "ubuntu",
        "category": "iniciante",
        "short_description": "Feito pela System76, com cara e produtividade parecidas com o macOS.",
        "long_description": "Pop!_OS usa o COSMIC, um ambiente próprio com foco em produtividade e organização de janelas. Tem excelente suporte a placas NVIDIA de fábrica, o que é raro entre distros voltadas a iniciantes.",
        "nvidia_support": "sim (imagem dedicada NVIDIA)",
        "has_good_docs": True,
        "default_de": "COSMIC (base GNOME)",
        "official_url": "https://pop.system76.com",
    },
    {
        "slug": "elementary",
        "name": "elementary OS",
        "base_slug": "ubuntu",
        "category": "iniciante",
        "short_description": "Visual muito próximo ao macOS, com atenção a detalhes de design.",
        "long_description": "elementary OS usa o Pantheon, um ambiente autoral com forte identidade visual inspirada no macOS. É opinativo — prioriza consistência visual acima de flexibilidade.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "Pantheon",
        "official_url": "https://elementary.io",
    },
    {
        "slug": "mx-linux",
        "name": "MX Linux",
        "base_slug": "debian",
        "category": "leve",
        "short_description": "Leve, estável, ótima para computadores mais antigos.",
        "long_description": "MX Linux combina a base sólida do Debian com o XFCE, um ambiente leve. É uma das distros mais recomendadas para reviver notebooks antigos sem abrir mão de uma boa experiência de uso.",
        "nvidia_support": "moderado",
        "has_good_docs": True,
        "default_de": "XFCE",
        "official_url": "https://mxlinux.org",
    },
    {
        "slug": "antix",
        "name": "antiX",
        "base_slug": "debian",
        "category": "leve",
        "short_description": "Extremamente leve, focada em máquinas muito antigas.",
        "long_description": "antiX é voltada especificamente para hardware muito limitado — roda em máquinas que outras distros nem tentariam suportar bem. Usa gerenciadores de janela leves como IceWM.",
        "nvidia_support": "não recomendado",
        "has_good_docs": True,
        "default_de": "IceWM / Fluxbox",
        "official_url": "https://antixlinux.com",
    },
    {
        "slug": "kali",
        "name": "Kali Linux",
        "base_slug": "debian",
        "category": "seguranca",
        "short_description": "Voltada para testes de invasão e segurança ofensiva.",
        "long_description": "Kali vem com centenas de ferramentas de pentest e análise forense pré-instaladas. Não é recomendada como sistema do dia a dia — é uma ferramenta de trabalho especializada.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "GNOME / XFCE",
        "official_url": "https://www.kali.org",
    },
    {
        "slug": "parrot-os",
        "name": "Parrot OS",
        "base_slug": "debian",
        "category": "seguranca",
        "short_description": "Alternativa ao Kali, também focada em segurança e privacidade.",
        "long_description": "Parrot OS cobre o mesmo público do Kali (pentest, forense), mas com foco extra em anonimato e privacidade, além de ser um pouco mais leve no dia a dia.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "MATE",
        "official_url": "https://www.parrotsec.org",
    },

    # --- Derivadas de Fedora ---
    {
        "slug": "nobara",
        "name": "Nobara",
        "base_slug": "fedora",
        "category": "jogos",
        "short_description": "Fedora otimizada para jogos, mantida por um ex-desenvolvedor do Proton.",
        "long_description": "Nobara parte do Fedora e já vem com todas as otimizações de jogos, codecs e drivers configurados de fábrica — o oposto do minimalismo do Fedora puro.",
        "nvidia_support": "sim (otimizado)",
        "has_good_docs": True,
        "default_de": "GNOME / KDE Plasma",
        "official_url": "https://nobaraproject.org",
    },
    {
        "slug": "bazzite",
        "name": "Bazzite",
        "base_slug": "fedora",
        "category": "jogos",
        "short_description": "Fedora Atomic voltado a jogos, com atualizações à prova de erro.",
        "long_description": "Bazzite usa a tecnologia de imagem imutável do Fedora Atomic — o sistema base não muda, o que reduz drasticamente o risco de quebrar algo em uma atualização. Muito usado em handhelds tipo Steam Deck.",
        "nvidia_support": "sim (otimizado)",
        "has_good_docs": True,
        "default_de": "GNOME / KDE Plasma",
        "official_url": "https://bazzite.gg",
    },

    # --- Derivadas de Arch ---
    {
        "slug": "steamos",
        "name": "SteamOS",
        "base_slug": "arch",
        "category": "jogos",
        "short_description": "A distro por trás do Steam Deck, focada 100% em jogos.",
        "long_description": "SteamOS é o sistema da Valve, otimizado para rodar em modo controle (Steam Big Picture) e maximizar compatibilidade de jogos via Proton.",
        "nvidia_support": "sim (otimizado para NVIDIA)",
        "has_good_docs": True,
        "default_de": "Steam Big Picture / KDE Plasma",
        "official_url": "https://store.steampowered.com/steamos",
    },
    {
        "slug": "chimeraos",
        "name": "ChimeraOS",
        "base_slug": "steamos",
        "category": "jogos",
        "short_description": "Transforma qualquer PC em algo parecido com um Steam Deck.",
        "long_description": "ChimeraOS pega a filosofia do SteamOS e a torna instalável em qualquer PC, entregando uma experiência de console em hardware genérico.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "Steam Big Picture",
        "official_url": "https://chimeraos.org",
    },
    {
        "slug": "garuda",
        "name": "Garuda Linux (Gaming)",
        "base_slug": "arch",
        "category": "jogos",
        "short_description": "Arch pré-configurado, visual chamativo e voltado a jogos.",
        "long_description": "Garuda entrega tudo que o Arch puro exige configurar manualmente, com um visual customizado (KDE Dr460nized) e ferramentas de sistema como o Garuda Assistant.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "KDE Plasma (Dr460nized)",
        "official_url": "https://garudalinux.org",
    },
    {
        "slug": "cachyos",
        "name": "CachyOS",
        "base_slug": "arch",
        "category": "avancado",
        "short_description": "Arch otimizado para performance, com pacotes compilados para hardware moderno.",
        "long_description": "CachyOS foca em performance bruta, usando repositórios com otimizações de compilação (x86-64-v3) e um kernel ajustado. Boa escolha pra quem já manja de Arch e quer espremer desempenho do hardware.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "KDE Plasma",
        "official_url": "https://cachyos.org",
    },
    {
        "slug": "blackarch",
        "name": "BlackArch",
        "base_slug": "arch",
        "category": "seguranca",
        "short_description": "Arch com um arsenal gigante de ferramentas de segurança ofensiva.",
        "long_description": "BlackArch é pro público avançado de pentest que já domina Arch e quer um repositório gigantesco de ferramentas de segurança sobre essa base.",
        "nvidia_support": "sim (configuração manual)",
        "has_good_docs": True,
        "default_de": "nenhum (à escolha)",
        "official_url": "https://blackarch.org",
    },

    # --- Nacionais / casos especiais ---
    {
        "slug": "biglinux",
        "name": "BigLinux",
        "base_slug": "arch",
        "category": "iniciante",
        "short_description": "Distro brasileira baseada em Arch/Manjaro, focada em facilidade.",
        "long_description": "BigLinux é mantida no Brasil e já resolve de fábrica questões comuns por aqui, como compatibilidade com sites de bancos e serviços do governo.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "KDE Plasma",
        "official_url": "https://www.biglinux.com.br",
    },
    {
        "slug": "regata-os",
        "name": "Regata OS",
        "base_slug": "opensuse-leap",
        "category": "iniciante",
        "short_description": "Distro brasileira voltada a jogos e produtividade.",
        "long_description": "Regata OS é outra distro nacional, com foco em jogos e boa compatibilidade com serviços brasileiros, incluindo bancos.",
        "nvidia_support": "sim",
        "has_good_docs": True,
        "default_de": "KDE Plasma",
        "official_url": "https://regataos.com.br",
    },
    {
        "slug": "puppy",
        "name": "Puppy Linux",
        "base_slug": None,
        "category": "leve",
        "short_description": "Extremamente leve, roda inteiro na memória RAM.",
        "long_description": "Puppy Linux é minúsculo (poucas centenas de MB) e pode rodar inteiramente carregado na RAM, tornando-o uma das opções mais leves que existem para hardware muito antigo.",
        "nvidia_support": "não recomendado",
        "has_good_docs": True,
        "default_de": "JWM / Openbox",
        "official_url": "http://puppylinux.com",
    },
]


DESKTOP_ENVIRONMENTS = [
    {
        "slug": "gnome",
        "name": "GNOME",
        "ram_consumption": "Alta (~800MB+)",
        "visual_style": "Moderna e minimalista",
        "features": "Recursos integrados, flatpak nativo",
        "recommended_for": "Usuários modernos e iniciantes",
    },
    {
        "slug": "kde-plasma",
        "name": "KDE Plasma",
        "ram_consumption": "Moderada (~500-700MB)",
        "visual_style": "Tradicional e altamente customizável",
        "features": "Recursos avançados, aparência rica",
        "recommended_for": "Quem gosta de personalizar tudo",
    },
    {
        "slug": "xfce",
        "name": "XFCE",
        "ram_consumption": "Baixa (~300-500MB)",
        "visual_style": "Clássica, leve e funcional",
        "features": "Simples, eficiente, altamente leve",
        "recommended_for": "PCs antigos, quem prioriza leveza",
    },
    {
        "slug": "lxqt",
        "name": "LXQt",
        "ram_consumption": "Muito baixa (~200-400MB)",
        "visual_style": "Muito leve e modular",
        "features": "Base Qt, minimalista",
        "recommended_for": "Netbooks, PCs muito fracos",
    },
    {
        "slug": "cinnamon",
        "name": "Cinnamon",
        "ram_consumption": "Moderada (~400-600MB)",
        "visual_style": "Elegante e familiar (estilo Windows)",
        "features": "Recursos modernos com aparência clássica",
        "recommended_for": "Iniciantes, ex-usuários do Windows",
    },
    {
        "slug": "mate",
        "name": "MATE",
        "ram_consumption": "Moderada (~400-600MB)",
        "visual_style": "Clássica (base GNOME 2)",
        "features": "Equilíbrio entre leveza e funcionalidade",
        "recommended_for": "Migração do GNOME antigo",
    },
    {
        "slug": "sway",
        "name": "Sway",
        "ram_consumption": "Muito baixa (<200MB)",
        "visual_style": "Tiling minimalista (Wayland)",
        "features": "Controle total via teclado, 100% Wayland",
        "recommended_for": "Usuários avançados, produtividade",
    },
    {
        "slug": "hyprland",
        "name": "Hyprland",
        "ram_consumption": "Baixa a moderada (~200-400MB)",
        "visual_style": "Tiling dinâmica e moderna (Wayland)",
        "features": "Efeitos gráficos e animações leves",
        "recommended_for": "Quem quer estilo e performance",
    },
]


# Cada pergunta tem: texto, ordem, e opções.
# Cada opção tem: texto e um dicionário de pesos {slug_da_distro: pontos}.
# O slug precisa bater com um slug em DISTROS.

QUIZ_QUESTIONS = [
    {
        "order": 1,
        "text": "Ao configurar algo novo no computador, você prefere entender e ajustar cada detalhe, ou prefere que já venha pronto para uso?",
        "options": [
            {
                "text": "Gosto de entender e ajustar",
                "weights": {"arch": 3, "cachyos": 3, "gentoo": 3, "void": 2, "fedora": 1},
            },
            {
                "text": "Prefiro que já funcione",
                "weights": {"zorin": 3, "mint": 3, "ubuntu": 2, "pop-os": 2, "biglinux": 2},
            },
        ],
    },
    {
        "order": 2,
        "text": "Pensando na aparência, qual sistema você já usou e gostou mais?",
        "options": [
            {
                "text": "Windows",
                "weights": {"zorin": 3, "mint": 2, "biglinux": 1},
            },
            {
                "text": "macOS",
                "weights": {"pop-os": 3, "elementary": 3},
            },
            {
                "text": "Não tenho preferência / tanto faz",
                "weights": {"ubuntu": 2, "fedora": 1, "mint": 1},
            },
        ],
    },
    {
        "order": 3,
        "text": "Você joga jogos no computador com alguma frequência?",
        "options": [
            {
                "text": "Sim, é uma prioridade",
                "weights": {"nobara": 3, "bazzite": 3, "steamos": 3, "cachyos": 2, "garuda": 2},
            },
            {
                "text": "Às vezes, mas não é o foco principal",
                "weights": {"pop-os": 2, "fedora": 1, "mint": 1},
            },
            {
                "text": "Praticamente não jogo",
                "weights": {"debian": 1, "mx-linux": 1, "opensuse-leap": 1},
            },
        ],
    },
    {
        "order": 4,
        "text": "Seu computador tem uma placa de vídeo NVIDIA?",
        "options": [
            {
                "text": "Sim",
                "weights": {"pop-os": 3, "nobara": 2, "bazzite": 2, "steamos": 2, "cachyos": 1},
            },
            {
                "text": "Não, ou não sei",
                "weights": {},
            },
        ],
    },
    {
        "order": 5,
        "text": "Como está o computador que você vai usar?",
        "options": [
            {
                "text": "Novo ou razoavelmente recente",
                "weights": {},
            },
            {
                "text": "Um pouco antigo, mas funcional",
                "weights": {"mx-linux": 2, "mint": 1},
            },
            {
                "text": "Bem antigo ou limitado",
                "weights": {"antix": 3, "puppy": 3, "mx-linux": 2},
            },
        ],
    },
    {
        "order": 6,
        "text": "Se você tiver uma dúvida ou problema, prefere resolver sozinho pesquisando, ou depender de suporte oficial?",
        "options": [
            {
                "text": "Gosto de pesquisar e resolver sozinho",
                "weights": {"arch": 2, "void": 2, "gentoo": 2, "debian": 1},
            },
            {
                "text": "Prefiro algo com boa documentação e comunidade grande",
                "weights": {"ubuntu": 2, "fedora": 2, "mint": 2, "opensuse-leap": 1},
            },
        ],
    },
    {
        "order": 7,
        "text": "O quanto você se importa com coleta de dados e privacidade?",
        "options": [
            {
                "text": "Me importo bastante",
                "weights": {"debian": 2, "void": 2, "mx-linux": 1},
            },
            {
                "text": "Me importo um pouco, mas não é decisivo",
                "weights": {"fedora": 1, "ubuntu": 1, "zorin": 1},
            },
            {
                "text": "Não é uma prioridade pra mim",
                "weights": {},
            },
        ],
    },
    {
        "order": 8,
        "text": "Você prefere um sistema que muda pouco com o tempo, ou um que está sempre recebendo as versões mais novas de tudo?",
        "options": [
            {
                "text": "Prefiro estabilidade, mudar pouco",
                "weights": {"debian": 3, "mint": 2, "opensuse-leap": 2, "mx-linux": 1},
            },
            {
                "text": "Prefiro estar sempre atualizado",
                "weights": {"arch": 3, "opensuse-tumbleweed": 3, "cachyos": 2, "void": 2},
            },
        ],
    },
]
